name = "Replicated Docs"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE.md"
description = "Theme for the Replicated docs site."
homepage = "https://github.com/replicatedhq/blank/"
tags = []
features = []
min_version = 0.19

[author]
  name = "Replicated"
  homepage = "https://github.com/replicatedhq"